ALTER SESSION ENABLE PARALLEL DDL;

CREATE INDEX I_PROFILING_7 ON PROFILING(ID, CLIENT, ENVIRONMENT) PARALLEL 10;
CREATE INDEX I_CPU_USAGE_2 ON CPU_USAGE(ID, CLIENT, ENVIRONMENT) PARALLEL 10;
CREATE INDEX I_MEMORY_USAGE_2 ON MEMORY_USAGE(ID, CLIENT, ENVIRONMENT) PARALLEL 10;